# Generated by Django 4.2.5 on 2024-03-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('landmarks', models.TextField()),
            ],
        ),
    ]
