# Generated by Django 4.2.5 on 2024-03-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolpoints',
            name='co_ordinator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rolpoints',
            name='contact',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
