# Generated by Django 4.2.5 on 2024-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0004_alter_rolpoints_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolpoints',
            name='google_map_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rolpoints',
            name='image',
            field=models.ImageField(blank=True, upload_to='google_map_image/'),
        ),
    ]
